In [1]:
from FPL_helper_classes import Team_helper, Player_helper

## Scrape team data from the internet and import player data from CSV files

In [2]:
team_helper = Team_helper()
team_helper.get_season_table(2019)

player_helper = Player_helper()
player_helper.read_all_player_data('2018-19')

In [3]:
#print(team_helper.team_dict['Man Utd'])
#team_helper.calculate_form(5)
#print(team_helper.form_dict['Everton'])
#print(player_helper.player_stat_dict)

## Detailed printout to see exact statistics after a player scores a goal

In [4]:
player_dict = player_helper.player_stat_dict
print("[Assists, Clean Sheets, Goals, Minutes, team against, points]")

for player_name, player_stats in player_dict.items():
    if sum(player_stats)[2] > 0:
        print(player_name)
        print("[A, C, G, M, O, P]")

        for i in range(len(player_stats)-1):
            if player_stats[i][2] == 1:
                print(player_stats[i+1])


[Assists, Clean Sheets, Goals, Minutes, team against, points]
Aaron_Lennon_83
[A, C, G, M, O, P]
[ 0  0  0 90  5  1]
Aaron_Mooy_199
[A, C, G, M, O, P]
[ 0  0  0  8 17  1]
Aaron_Ramsey_14
[A, C, G, M, O, P]
[ 0  0  0 10 11  1]
[ 0  0  0 31 19  1]
[ 0  1  0 90 14  3]
[ 0  0  0 45  8  1]
Abdoulaye_Doucouré_390
[A, C, G, M, O, P]
[ 0  0  1 90  8  8]
[ 1  0  0 90  5  5]
[ 0  0  0 55  2  0]
[ 0  0  1 90  9  7]
[ 0  0  0 90  1  2]
Aboubakar_Kamara_189
[A, C, G, M, O, P]
[ 0  0  1 45 14  5]
[ 0  0  0 90 19  2]
[0 0 0 0 4 0]
Adam_Smith_29
[A, C, G, M, O, P]
[ 0  0  0 77  4  1]
Adama_Traoré_500
[A, C, G, M, O, P]
[ 0  0  0 24  4  1]
Ainsley_Maitland-Niles_20
[A, C, G, M, O, P]
[ 0  0  0 90  9  2]
Aleksandar_Mitrovic_480
[A, C, G, M, O, P]
[ 1  0  2 90  4 16]
[ 0  0  0 90 13  2]
[ 0  0  0 90  8  1]
[ 0  0  0 90  1  2]
[ 0  1  0 90  5  2]
Alex_Iwobi_15
[A, C, G, M, O, P]
[ 1  0  0 45 19  4]
[ 0  0  0 45  3  1]
[ 1  1  0 74 16  6]
Alex_Pritchard_206
[A, C, G, M, O, P]
[ 0  1  0 90 20  3]
Alexandre_

## Statistics of players after scoring for players with atleast 10 goals

In [5]:
import numpy as np

np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})

for player_name, player_stats in player_dict.items():
    if sum(player_stats)[2] > 9:
        print(player_name, sum(player_stats)[2], "[A, C, G, M, O, P]")


        average = sum(player_stats)/sum([min(1, i[3]) for i in player_stats])
        print("Average: ", average)
    
        counter = np.array([0,0,0,0,0,0])
        games = 0
        for i in range(len(player_stats)-1):
            if player_stats[i][2] == 1:
                counter = counter + player_stats[i+1]
                games += 1
    
        print("After goal: ", counter/games, "\n")

Aleksandar_Mitrovic_480 11 [A, C, G, M, O, P]
Average:  [0.108 0.135 0.297 88.649 10.865 3.622]
After goal:  [0.200 0.200 0.400 90.000 6.200 4.600] 

Alexandre_Lacazette_22 13 [A, C, G, M, O, P]
Average:  [0.343 0.171 0.371 71.343 11.943 4.743]
After goal:  [0.364 0.182 0.273 75.091 13.364 4.091] 

Anthony_Martial_301 10 [A, C, G, M, O, P]
Average:  [0.148 0.185 0.370 59.741 14.519 4.519]
After goal:  [0.000 0.125 0.500 46.250 9.875 4.500] 

Ashley_Barnes_85 12 [A, C, G, M, O, P]
Average:  [0.081 0.189 0.324 64.270 11.135 3.297]
After goal:  [0.111 0.111 0.333 87.222 10.889 3.778] 

Ayoze_Pérez_326 12 [A, C, G, M, O, P]
Average:  [0.054 0.297 0.324 78.811 10.541 3.811]
After goal:  [0.000 0.333 0.500 89.333 9.500 4.333] 

Callum_Wilson_43 14 [A, C, G, M, O, P]
Average:  [0.400 0.300 0.467 84.267 13.867 5.600]
After goal:  [0.300 0.100 0.200 63.000 11.800 3.300] 

Chris_Wood_87 10 [A, C, G, M, O, P]
Average:  [0.079 0.184 0.263 67.895 10.842 3.447]
After goal:  [0.000 0.333 0.500 85.500

## Statistics of players after getting more than 5 points in 2 consecutive games

In [6]:
import numpy as np

np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})

for player_name, player_stats in player_dict.items():
    if sum(player_stats)[3] > 2000:
        print(player_name, sum(player_stats)[2], "[A, C, G, M, O, P]")


        average = sum(player_stats)/sum([min(1, i[3]) for i in player_stats])
        print("Average: ", average)
    
        counter = np.array([0,0,0,0,0,0])
        games = 0
        for i in range(len(player_stats)-2):
            if player_stats[i][5] >5:
                if player_stats[i][5] >5:
                    counter = counter + player_stats[i+1]
                    games += 1
    
        print("After 2 good games: ", counter/games, "\n")

Aaron_Mooy_199 3 [A, C, G, M, O, P]
Average:  [0.034 0.103 0.103 80.207 13.793 2.621]
After 2 good games:  [0.000 0.000 0.000 53.333 9.000 1.667] 

Aaron_Wan-Bissaka_145 0 [A, C, G, M, O, P]
Average:  [0.086 0.343 0.000 89.543 11.600 3.429]
After 2 good games:  [0.000 0.182 0.000 88.545 9.818 2.273] 

Abdoulaye_Doucouré_390 5 [A, C, G, M, O, P]
Average:  [0.200 0.143 0.143 87.457 10.971 3.543]
After 2 good games:  [0.111 0.111 0.222 86.111 7.000 3.444] 

Adam_Smith_29 1 [A, C, G, M, O, P]
Average:  [0.040 0.320 0.040 82.680 16.640 2.800]
After 2 good games:  [0.000 0.375 0.000 77.125 10.250 2.625] 

Aleksandar_Mitrovic_480 11 [A, C, G, M, O, P]
Average:  [0.108 0.135 0.297 88.649 10.865 3.622]
After 2 good games:  [0.167 0.000 0.500 90.000 4.833 4.667] 

Alex_McCarthy_328 0 [A, C, G, M, O, P]
Average:  [0.000 0.160 0.000 90.000 15.520 2.920]
After 2 good games:  [0.000 0.250 0.000 90.000 9.750 2.000] 

Alex_Pritchard_206 2 [A, C, G, M, O, P]
Average:  [0.000 0.233 0.067 69.300 13.333 2

Felipe Anderson_Pereira Gomes_465 9 [A, C, G, M, O, P]
Average:  [0.167 0.194 0.250 84.583 10.611 4.306]
After 2 good games:  [0.111 0.111 0.111 87.444 8.889 3.222] 

Fernando_Luiz Rosa_272 1 [A, C, G, M, O, P]
Average:  [0.103 0.414 0.034 81.897 13.586 2.724]
After 2 good games:  [0.000 0.667 0.000 54.333 9.667 1.333] 

Francisco_Femenía Far_383 1 [A, C, G, M, O, P]
Average:  [0.034 0.138 0.034 70.448 13.241 2.276]
After 2 good games:  [0.200 0.200 0.000 65.600 9.800 3.200] 

Georginio_Wijnaldum_252 3 [A, C, G, M, O, P]
Average:  [0.029 0.514 0.086 77.800 11.314 3.086]
After 2 good games:  [0.000 0.750 0.000 80.250 10.250 2.500] 

Gerard_Deulofeu_394 10 [A, C, G, M, O, P]
Average:  [0.167 0.300 0.333 68.800 12.800 4.433]
After 2 good games:  [0.000 0.143 0.286 70.714 13.571 3.429] 

Glenn_Murray_62 13 [A, C, G, M, O, P]
Average:  [0.026 0.105 0.342 65.816 10.895 3.395]
After 2 good games:  [0.000 0.143 0.143 56.286 12.571 2.143] 

Granit_Xhaka_17 4 [A, C, G, M, O, P]
Average:  [0.103 

Average:  [0.000 0.241 0.000 74.552 13.448 1.931]
After 2 good games:  [nan nan nan nan nan nan] 

Mohamed_Salah_253 22 [A, C, G, M, O, P]
Average:  [0.316 0.553 0.579 85.632 10.421 6.816]
After 2 good games:  [0.421 0.474 0.579 84.895 8.947 7.211] 

Moussa_Sissoko_369 0 [A, C, G, M, O, P]
Average:  [0.103 0.379 0.000 80.310 13.310 2.621]
After 2 good games:  [0.000 0.000 0.000 60.000 10.000 1.333] 

N'Golo_Kanté_126 4 [A, C, G, M, O, P]
Average:  [0.111 0.389 0.111 85.889 11.333 3.222]
After 2 good games:  [0.000 0.143 0.000 88.000 10.571 2.143] 

Nathan_Aké_31 4 [A, C, G, M, O, P]
Average:  [0.026 0.263 0.105 89.763 10.947 3.158]
After 2 good games:  [0.091 0.273 0.091 90.000 12.091 3.273] 

Nathan_Redmond_343 6 [A, C, G, M, O, P]
Average:  [0.132 0.237 0.158 86.105 10.211 3.605]
After 2 good games:  [0.000 0.000 0.167 82.500 13.000 2.500] 

Neil_Etheridge_88 0 [A, C, G, M, O, P]
Average:  [0.000 0.263 0.000 90.000 10.789 4.053]
After 2 good games:  [0.000 0.300 0.000 90.000 12.100 5

<ipython-input-6-c3b2e9fe73c9>:21: RuntimeWarning: invalid value encountered in true_divide
  print("After 2 good games: ", counter/games, "\n")


In [9]:
np.set_printoptions(formatter={'float': lambda x: "{0:0.1f}".format(x)})
num_games = 5

for player_name, player_stats in player_dict.items():
    if sum(player_stats[:num_games])[2] >= 4:
        print(player_name, "[A, C, G, M, O, P]")


        total = sum(player_stats)
        first_games = sum(player_stats[:num_games])


        print(f"First {num_games} game stats: ", first_games)
        print("   extrapolated up: ", first_games*(38/num_games))
        print("            Actual: ", total, "\n")  



Aleksandar_Mitrovic_480 [A, C, G, M, O, P]
First 5 game stats:  [  1   0   4 450  44  31]
   extrapolated up:  [7.6 0.0 30.4 3420.0 334.4 235.6]
            Actual:  [   4    5   11 3280  402  134] 

Eden_Hazard_122 [A, C, G, M, O, P]
First 5 game stats:  [  2   1   5 306  33  47]
   extrapolated up:  [15.2 7.6 38.0 2325.6 250.8 357.2]
            Actual:  [  15   12   16 2918  408  238] 

Glenn_Murray_62 [A, C, G, M, O, P]
First 5 game stats:  [  0   0   4 450  69  27]
   extrapolated up:  [0.0 0.0 30.4 3420.0 524.4 205.2]
            Actual:  [   1    4   13 2501  414  129] 

Romelu_Lukaku_306 [A, C, G, M, O, P]
First 5 game stats:  [  0   1   4 383  53  29]
   extrapolated up:  [0.0 7.6 30.4 2910.8 402.8 220.4]
            Actual:  [   1    4   12 2126  392  115] 

Sadio_Mané_251 [A, C, G, M, O, P]
First 5 game stats:  [  0   3   4 430  57  41]
   extrapolated up:  [0.0 22.8 30.4 3268.0 433.2 311.6]
            Actual:  [   3   19   22 3076  396  231] 

